### ISSUE TITLE
 ImportError: cannot import name '_levelNames' from 'logging'

### ISSUE THREAD

**Issue by prapkengr** [natural/java2python#63]
After solving couple of issues .. like .. 
`except ........ as exc:`
Now seeing 
` ImportError: cannot import name '_levelNames' from 'logging'`
Both in 
Windows 10 x64, Python 2.7 / 3 / 3.7
Linux - Raspberry Raspbian (Debian).

**Comment by phs-sakshi** [comment]
how did you resolve this issue?
